### ISSUE TITLE
Action when clicking Group

### ISSUE THREAD

**Issue by xang1234** [mattflor/chorddiag#10]
Hi,

Bravo!!!Great package!!! Keep up the good work. Would it be possible to add an action when a group/node is clicked? The total for a group is already displayed upon hover and the groups linking to it are highlighted. To make it even better, it would be great to allow an action to analyse these links via a click action.

Correct me if I am wrong but currently there is only an action when the arc/link is clicked with the indices stored in d.source.index and d.target.index.

Cheers

**Comment by mattflor** [comment]
There you go: https://github.com/mattflor/chorddiag/releases/tag/v0.1.2
