### ISSUE TITLE
Long labels cut off

### ISSUE THREAD

**Issue by jelias1** [mattflor/chorddiag#16]
I am running into a problem where labels are being cut off on the plot. Specifically the labels coming from the top and bottom of the chord diagram. I have tried increasing margins and decreasing font size, but this only helps so much. Any recommendations I can try to fix this?

Thanks, and really easy package to work with!

**Comment by mattflor** [comment]
Use shorter labels. I'm afraid that's pretty much all you can do apart from what you have already done.
