### ISSUE TITLE
Color options for semi-large N (N=38)?

### ISSUE THREAD

**Issue by jeffcsauer** [mattflor/chorddiag#27]
Hi all, 

Awesome package and was able to get it off the ground with little issue! Props to Matt and the other contributors. 

I have a quick of question I (hope) is straightforward. 

I've managed to get the chorddiag() running (see code on my repo: https://github.com/jefferycsauer/gic_chord_diag). However, I'm struggling to understand how colors work on the diagram. I have 38 countries total, so I would like to color each country uniquely. When I attempt to pass a random selection of colors through the diagram, it does nothing (for example, groupColors = rainbow(38)). What am I doing wrong? Do I have to many groups?

**Comment by jefferycsauer** [comment]
Added URL of repo

**Comment by jeffcsauer** [comment]
Solved with mattflor's prior solution: 

groupColors <- viridis_pal()(38)           # n discrete Viridis colors
groupColors <- substr(groupColors, 0, 7)  # get rid of transparency characters ('FF')
