### ISSUE TITLE
 chorddiag plots are not visible when using dynamically generated tabs

### ISSUE THREAD

**Issue by yuliaUU** [mattflor/chorddiag#36]
I want to dynamically generate tabs, and each tab plot the corddiag plot
```
library(igraph)
library(tidygraph)
library(chorddiag)

m <- matrix(c(11975,  5871, 8916, 2868,
               1951, 10048, 2060, 6171,
               8010, 16145, 8090, 8045,
               1013,   990,  940, 6907),
               byrow = TRUE,
               nrow = 4, ncol = 4)
groupnames <- c("black", "blonde", "brown", "red")
row.names(m) <- groupnames
colnames(m) <- groupnames
```

```
## First learned languages {.tabset .tabset-fade .tabset-pills}

```{r echo=FALSE, fig.height=6, fig.width=6, warning=FALSE, results='asis'}
for (i in 1:3) {
  cat("###", paste("Tab ",i), '{-}',  '\n\n')
  print(chorddiag(m))
  cat( '\n\n')
}
```
everything works pretty well in Rmarkdown window, but when I knot I can't generate plots. I also tried to use htmltools::tagList as it did worked for plotly library, it does create a space but no plots show up

I also get an error :/chunk_output/42CC8C6564F105CC/4A1ED7C7/c3rny570vwpsr/000029.html?viewer_pane=1&capabilities=1 not found

**Comment by mattflor** [comment]
Could you provide a minimal reproducible example? Then I could look into this.
