### ISSUE TITLE
conditional display of tooltip?

### ISSUE THREAD

**Issue by jaehyeon-kim** [mattflor/chorddiag#4]
Hi

I find this package quite handy. 

Sometimes there is no value from right to left and, in this case, it might be better not to show. Specifically the tooltip shows the following when right to left is 0.

`# original`
`A -> B: 2.15%`
`B -> A: 0%`

If the line 86 of chorddiag.js is modified as following, the second line is not shown as following.

`#86 of chorddiag.js`
`return dir1 + (vji > 0 ? "</br>" + dir2 : "");`

`# modified`
`A -> B: 2.15%`

I wonder if an option to hide tooltip entry when value is 0 may be good.

Thanks.

Regards
Jaehyeon

**Comment by mattflor** [comment]
Hi @jaehyeon-kim, sorry for the delayed reply. I haven't yet found the time to look into your suggestion but I'll probably manage this week...
