### ISSUE TITLE
How to add another layer for a group over the chord segments?

### ISSUE THREAD

**Issue by KDIncognito** [mattflor/chorddiag#7]
Hi,

I love this example. This perhaps is the simplest way of creating a circle plot. I have a migration data very similar to https://gjabel.wordpress.com/2014/03/28/circular-migration-flow-plots-in-r/, and I am trying to add a group over the countries. For example, I want to group China, Thailand, Malaysia, Indonesia, Philippines into a group by continent (Asia in this case). How do I do that? I came across this example on [stack](http://stackoverflow.com/questions/27500041/r-make-circle-chord-diagram-with-circlize-from-dataframe), but my data can not be fit into an adjacency matrix. It is a square matrix with regions and countries separated commas (Names in rows and columns will be similar to \Asia,India\Asia,Philippines\ etc.). Please help!

Thank you!

Regards,
KD

**Comment by mattflor** [comment]
Sorry, I'm not sure I understand what you mean by "add a group over the countries". Like in the car brand / car model example from the stackoverflow you referenced, http://stackoverflow.com/a/36809503? That's not currently possible with the chorddiag package.

**Comment by KDIncognito** [comment]
Sorry for the delay in closing this issue. I understand that's not currently in the scope. Thank you!
